# SPDX-FileCopyrightText: 2023-present University of Vienna
# SPDX-License-Identifier: GPL-3.0-or-later

"""Stub file for the compiled CUDA extension module ``python._core_cuda``."""

from typing import List, Optional

import numpy as np

def get_num_devices() -> int: ...
def set_device(device_id: Optional[int]) -> None: ...
def get_device() -> int: ...
def get_free_device_memory() -> int: ...
def get_free_host_memory() -> int: ...
def get_host_memory_diff(nx: int, ny: int, length: int, num_lags: int) -> int: ...
def get_host_memory_fft(nx: int, ny: int, length: int, num_lags: int) -> int: ...
def check_host_memory_diff(nx: int, ny: int, length: int, num_lags: int) -> bool: ...
def check_host_memory_fft(nx: int, ny: int, length: int, num_lags: int) -> bool: ...
def ddm_diff_cuda(
    img_seq: np.ndarray,
    lags: List[int],
    nx: int,
    ny: int,
    window: np.ndarray,
) -> np.ndarray: ...
def ddm_fft_cuda(
    img_seq: np.ndarray,
    lags: List[int],
    nx: int,
    ny: int,
    nt: int,
    window: np.ndarray,
) -> np.ndarray: ...
