name: Build and test

on:
  # trigger on all commits to main and develop
  # NOTE: pushes to main should be protected by branch protection rules
  push:
    branches:
      - main
      - develop

  # trigger on pull requests to main and develop
  pull_request:
    branches:
      - main
      - develop

  # trigger on request
  workflow_dispatch:

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.14"]

    steps:
      - uses: actions/checkout@v4

      - name: 📦 Install uv
        uses: astral-sh/setup-uv@v5

      - name: 🐍 Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: 🏗️ Build package and install through uv
        run: |
          uv pip install --upgrade pip
          python install.py -v --uv --cpp --extras=test

      - name: 🧪 Run tests
        run: |
          pytest -v

  build-cuda:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubu24_T4, win11_x64_T4]
        python-version: ["3.9"] #["3.9", "3.14"]
        cuda-version: ["12.8.0"]

    steps:
      - uses: actions/checkout@v4

      - name: 🧑‍💻 Set up CUDA ${{ matrix.cuda-version }}
        id: cuda-toolkit
        uses: Jimver/cuda-toolkit@v0.2.30
        with:
          cuda: ${{ matrix.cuda-version }}
          method: network
          sub-packages: '["nvcc", "cudart", "nvml"]'
          non-cuda-sub-packages: '["libcufft"]'

      - name: ✅ Verify CUDA installation
        run: |
          echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
          echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
          nvcc -V

      - name: 📦 Install uv
        uses: astral-sh/setup-uv@v5

      - name: 🐍 Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: 🏗️ Build package and install through uv with CUDA support
        run: |
          uv pip install --upgrade pip
          python install.py -v --uv --gpu --extras=test

      - name: 🧪 Run tests with CUDA support
        run: |
          pytest -v
